<a href="index.php?name=addRower" class="btn btn-outline-blue mb-3"><i class="fas fa-plus pr-1"></i> Ajouter un rameur</a>

<?php if ($vars['rowers']) :?>
    <form action ="" method="POST">
        <div class="row ml-0 d-flex justify-content-xl-start justify-content-center mt-4">
            <?php foreach($vars['rowers'] as $rower): ?>

                <div class="pr-4 position-relative">
                    <div class="position-absolute" style="z-index:1;">
                        <a href="#" data-toggle="modal" data-target="#rower-<?=$rower['id']?>" class="btn btn-danger"><i class="fas fa-window-close"></i></a>
                    </div>
                    <div class="card card-list" style="width: 19em">
                        <img src="../uploads/rower/<?=$rower['picture'] ?>" class="d-block w-100" style="height: 300px">
                        <div class="card-body text-center">
                            <!-- TITRE -->
                            <h3 class="card-title text-center"><?=$rower['firstname']?> <?=$rower['lastname']?></h3>
                            <!-- BOUTON MODIFIER -->
                            <a href="index.php?name=addRower&id=<?=$rower['id'] ?>" class="btn btn-primary"><i class="fas fa-edit pr-1"></i>MODIFIER</a>

                        </div>
                    </div>
                </div>

                <!-- Modal de suppression -->
                <div class="modal fade" id="rower-<?=$rower['id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="exampleModalLabel">Attention</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Êtes-vous sûr de vouloir supprimer le rameur <b><?=$rower['firstname']?> <?=$rower['lastname']?></b>?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                <input type="hidden" name="picture-<?=$rower['id']?>" value="<?=$rower['picture']?>"/>
                                <button type="submit" name="delete-rower-<?=$rower['id']?>" class="btn btn-danger" value="<?=$rower['id']?>">Supprimer</button>
                            </div>
                        </div>
                    </div>
                </div>

            <?php endforeach ?>
        </div>
    </form>
<?php else:?>
    <p>Aucun rameur pour le moment.</p>
<?php endif;?>
