<!-- CODE HTML SPECIFIQUE A LA PAGE USER LIST -->

<div class="table-responsive-md mt-4 all">
    <a href="index.php?name=addUser" class="btn btn-primary mb-3"><i class="fas fa-plus pr-1"></i> Ajouter un utilisateur</a>
    <table class="table table-striped ">
        <thead>
        <tr>
            <th class="text-center" scope="col">ID</th>
            <th scope="col">Prénom</th>
            <th scope="col">Nom</th>
            <th scope="col">Email</th>
            <th scope="col">Rôle</th>
            <th scope="col" class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>


        <?php foreach($vars['users'] as $user): ?>
            <tr>
                <td class="text-center"><?=$user['id']?></td>
                <td><?=$user['firstname']?></td>
                <td><?=$user['lastname']?></td>
                <td><?=$user['email']?></td>
                <td>
                    <?php echo $user['role'] === 'ROLE_ADMIN' ? 'Admin' : 'Utilisateur' ?>
                </td>
                <td class="text-center">
                    <a href="#" data-toggle="modal" data-target="#user-<?=$user['id']?>"><i class="fa fa-trash text-danger mr-2 h5"></i></a>
                    <a href="index.php?name=addUser&id=<?=$user['id'] ?>"i class="fa fa-edit text-secondary mr-2 h5"></i></a>
                </td>
            </tr>

            <!-- Modal de suppression -->
            <?php if($_SESSION['user']['role'] !== 'ROLE_ADMIN') :?>
                <div class="modal fade" id="user-<?=$user['id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="exampleModalLabel">Désolé...</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Vous n'avez <b>pas les droits</b> pour supprimer un compte.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php else :?>
                <form method="POST">
                    <div class="modal fade" id="user-<?=$user['id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title text-danger" id="exampleModalLabel">Attention</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <?php if($user['email'] == $_SESSION['user']['email']) :?>
                                    <div class="modal-body">
                                        Vous êtes sur le point de supprimer <b>votre compte</b>.<br>
                                        Si vous cliquez sur "supprimer" vous serez déconnecté !
                                    </div>
                                <?php else :?>
                                    <div class="modal-body">
                                        Êtes-vous sûr de vouloir supprimer l'utilisateur <b><?=$user['firstname']?></b>?
                                    </div>
                                <?php endif ?>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                    <input type="hidden" name="name-<?=$user['id']?>" value="<?=$user['firstname']?> <?=$user['lastname']?>"/>
                                    <button type="submit" name="delete-user-<?=$user['id']?>" class="btn btn-danger" value="<?=$user['id']?>">Supprimer</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            <?php endif ?>
        <?php endforeach ?>

        </tbody>
    </table>
</div>




