<a href="index.php?name=addTrip" class="btn btn-outline-blue mb-3"><i class="fas fa-plus pr-1"></i> Ajouter une traversée</a>


<form action ="" method="POST">
    <div class="row ml-0 d-flex justify-content-xl-start justify-content-center mt-4">
        <?php foreach($vars['trips'] as $trip): ?>

            <div class="pr-4 position-relative">
                <div class="position-absolute" style="z-index:1;">
                    <a href="#" data-toggle="modal" data-target="#trip-<?=$trip['id']?>" class="btn btn-danger"><i class="fas fa-window-close"></i></a>
                </div>
                <div class="card card-list" style="width: 18rem;">
                    <?php if($trip['is_video']) :?>
                        <img src="http://i3.ytimg.com/vi/<?=$trip['video_url']?>/maxresdefault.jpg" class="d-block w-100">
                    <?php else :?>
                        <img src="../uploads/trip/<?=$trip['picture'] ?>" class="d-block w-100">
                    <?php endif ;?>
                    <div class="card-body">
                        <!-- TITRE -->
                        <h3 class="card-title text-center mb-0"><?=$trip['date']?></h3>
                        <!-- ORDRE AFFICHAGE -->
                        <p class="text-center mb-4"><?=$trip['title']?></p>
                        <!-- BOUTON MODIFIER -->
                        <a href="index.php?name=addTrip&id=<?=$trip['id'] ?>" class="btn btn-primary d-block"><i class="fas fa-edit pr-1"></i>MODIFIER</a>

                    </div>
                </div>
            </div>

            <!-- Modal de suppression -->
            <?php if($_SESSION['user']['role'] !== 'ROLE_ADMIN') :?>
                <div class="modal fade" id="trip-<?=$trip['id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="exampleModalLabel">Désolé...</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Vous n'avez <b>pas les droits</b> pour supprimer une traversée.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php else :?>
                <div class="modal fade" id="trip-<?=$trip['id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="exampleModalLabel">Attention</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Êtes-vous sûr de vouloir supprimer la traversée <b><?=$trip['title']?></b>?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                <input type="hidden" name="title-<?=$trip['id']?>" value="<?=$trip['title']?>"/>
                                <input type="hidden" name="picture-<?=$trip['id']?>" value="<?=$trip['picture']?>"/>
                                <button type="submit" name="delete-trip-<?=$trip['id']?>" class="btn btn-danger" value="<?=$trip['id']?>">Supprimer</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif ;?>
        <?php endforeach ?>
    </div>
</form>
