
<form action="" id="file-upload-form" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">

    <div class="row">
        <div class="col-lg-4 col-xlg-3 col-md-12">
            <label class="col-md-12 pl-0 h3 text-primary text-center mb-2 pr-0" for="picture">Photo</label>
            <div class="parent-div d-flex justify-content-center position-relative">
                <input type="file" name="picture" id="file-upload" class="pointer" data-max-files="1" style="position:absolute;top:0;left:0;opacity:0"/>
                <span id="file-upload-btn" class="btn btn-primary"><i class="fa fa-download text-white pr-2" aria-hidden="true"></i>Drag or clic</span>
            </div>
            <div class="form-group col-md-12 py-2 mb-0">
                <label for="file-upload" id="file-drag" class="d-flex justify-content-center">
                    <!-- EDITION : si on a une photo on l'affiche et on passe le nom de cette photo dans un champ caché ! -->
                    <?php if($vars['oldPicture'] !== null) :?>
                        <input type="hidden" name="oldPicture" value="<?=$vars['oldPicture']?>">
                        <img id="file-image" src="../uploads/coordinate/<?=$vars['oldPicture']?>" class="hidden pt-2 d-block m-auto">
                    <?php else:?>
                        <img id="file-image" src="assets\img\download-icon.png" class="hidden pt-2 d-block m-auto">
                    <?php endif;?>
                    <div class="position-relative">
                        <div id="start" style="left: 0; top: 0; opacity: 0; position: absolute;">
                            <i class="fa fa-download" aria-hidden="true"></i>
                            <div></div>
                            <span id="file-upload-btn" class="btn btn-primary"></span>
                            <div id="notimage" class="hidden"></div>
                        </div>
                        <div id="response" class="hidden" style="opacity:0;display:none">
                            <div id="messages"></div>
                            <progress class="progress" id="file-progress" value="0">
                                <span>0</span>%
                            </progress>
                        </div>
                </label>
            </div>
        </div>
        <div class="parent-div d-flex justify-content-center flex-wrap">
            <p class="form-text text-center">Pour modifier une image téléchargez en une nouvelle. Sinon l'ancienne sera conservée !</p>
            <p class="text-secondary text-center">Taille max : <b>2 Mo</b></p>
            <?php if(!empty($vars['errors']) && isset($vars['errors']['picture'])):?>
                <p class="text-danger mb-0"><?=$vars['errors']['picture']?></p>
            <?php endif ?>
        </div>
    </div>

    <div class="col-lg-8 col-xlg-9 col-md-12">
        <div class="card">
            <div class="card-body">

                <div class="row mt-4" style="padding-left: 15px; padding-right: 15px">
                    <!-- DATE -->
                    <div class="form-group col-12 col-md-4 mb-4">
                        <label>Date</label>
                        <div class="col-md-12 border-bottom p-0">
                            <input type="date" name="date" value="<?=$vars['date']?>" class="form-control p-0 border-0">
                        </div>
                    </div>

                    <!-- HOUR -->
                    <div class="form-group col-12 col-md-4 mb-4">
                        <label>Horaire</label>
                        <div class="col-md-12 border-bottom p-0">
                            <input type="text" name="hour" value="<?=$vars['hour'] ?: '18h30' ?>" class="form-control p-0 border-0">
                        </div>
                        <?php if(!empty($vars['errors']) && isset($vars['errors']['hour'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['hour']?></p>
                        <?php endif ?>
                    </div>
                </div>

                <div class="row mt-4" style="padding-left: 15px; padding-right: 15px">
                    <!-- LATITUDE -->
                    <div class="form-group col-12 col-md-4 mb-4">
                        <label>Latitude</label>
                        <div class="col-md-12 border-bottom p-0">
                            <input type="text" name="latitude" value="<?=$vars['latitude']?>" class="form-control p-0 border-0">
                        </div>
                        <?php if(!empty($vars['errors']) && isset($vars['errors']['latitude'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['latitude']?></p>
                        <?php endif ?>
                    </div>

                    <!-- LONGITUDE -->
                    <div class="form-group col-12 col-md-4 mb-4">
                        <label>Longitude</label>
                        <div class="col-md-12 border-bottom p-0">
                            <input type="text" name="longitude" value="<?=$vars['longitude']?>" class="form-control p-0 border-0">
                        </div>
                        <?php if(!empty($vars['errors']) && isset($vars['errors']['longitude'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['longitude']?></p>
                        <?php endif ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="col-lg-4 col-xlg-3 col-md-12"></div>
    <div class="col-lg-8 col-xlg-9 col-md-12">
        <button type="submit" class="btn btn-success text-white mt-3"><i class="fas fa-check pr-1"></i><?php echo $vars['id'] ? 'MODIFIER' : 'CREER' ?></button>
    </div>
</form>
