
<form action="" id="file-upload-form" method="POST" class="form-horizontal form-material">

    <div class="col-lg-8 col-xlg-9 col-md-12">
        <div class="card">
            <div class="card-body">

                <div class="row mt-4" style="padding-left: 15px; padding-right: 15px">
                    <!-- DATE -->
                    <div class="form-group col-12 col-md-4 mb-4">
                        <label>Date</label>
                        <div class="col-md-12 border-bottom p-0">
                            <input type="date" name="date" value="<?=$vars['date']?>" class="form-control p-0 border-0">
                        </div>
                    </div>

                    <!-- HOUR -->
                    <div class="form-group col-12 col-md-4 mb-4">
                        <label>Horaire</label>
                        <div class="col-md-12 border-bottom p-0">
                            <input type="text" name="hour" value="<?=$vars['hour'] ?: '18h30' ?>" class="form-control p-0 border-0">
                        </div>
                        <?php if(!empty($vars['errors']) && isset($vars['errors']['hour'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['hour']?></p>
                        <?php endif ?>
                    </div>
                </div>

                <div class="row mt-4" style="padding-left: 15px; padding-right: 15px">
                    <!-- LATITUDE -->
                    <div class="form-group col-12 col-md-4 mb-4">
                        <label>Latitude</label>
                        <div class="col-md-12 border-bottom p-0">
                            <input type="text" name="latitude" value="<?=$vars['latitude']?>" class="form-control p-0 border-0">
                        </div>
                        <?php if(!empty($vars['errors']) && isset($vars['errors']['latitude'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['latitude']?></p>
                        <?php endif ?>
                    </div>

                    <!-- LONGITUDE -->
                    <div class="form-group col-12 col-md-4 mb-4">
                        <label>Longitude</label>
                        <div class="col-md-12 border-bottom p-0">
                            <input type="text" name="longitude" value="<?=$vars['longitude']?>" class="form-control p-0 border-0">
                        </div>
                        <?php if(!empty($vars['errors']) && isset($vars['errors']['longitude'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['longitude']?></p>
                        <?php endif ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="col-lg-4 col-xlg-3 col-md-12"></div>
    <div class="col-lg-8 col-xlg-9 col-md-12">
        <button type="submit" class="btn btn-success text-white mt-3"><i class="fas fa-check pr-1"></i><?php echo $vars['id'] ? 'MODIFIER' : 'CREER' ?></button>
    </div>
</form>
