<a href="index.php?name=addCoordinate" class="btn btn-outline-blue mb-3"><i class="fas fa-plus pr-1"></i> Ajouter une coordonnée</a>

<?php if ($vars['coordinates']) :?>
    <form action ="" method="POST">
        <div class="row ml-0 d-flex justify-content-xl-start justify-content-center mt-4">
            <?php foreach($vars['coordinates'] as $coordinate): ?>

                <div class="pr-lg-4 position-relative col-6 col-md-4 mb-2">
                    <div class="row bg-white p-3 align-items-center">
                        <div class="col-sm-12 col-md-4 text-center pb-4 pb-md-0">
                            <div class="flex justify-content-between">
                                <a href="#" data-toggle="modal" data-target="#coordinate-<?=$coordinate['id']?>" class="btn btn-danger"><i class="fas fa-window-close"></i></a>
                                <a href="index.php?name=addCoordinate&id=<?=$coordinate['id'] ?>" class="btn btn-primary"><i class="fas fa-edit"></i></a>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-8">
                            <h4 class="date"><?= utf8_encode(strftime("%A %d %B %G", strtotime($coordinate['date']))); ?></h4>
                            <p class="mb-0"><b>Latitude :</b><?=$coordinate['latitude']?></p>
                            <p><b>Longitude :</b><?=$coordinate['longitude']?></p>
                        </div>
                    </div>
                </div>

                <!-- Modal de suppression -->
                <div class="modal fade" id="coordinate-<?=$coordinate['id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="exampleModalLabel">Attention</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Êtes-vous sûr de vouloir supprimer la coordonnée du <b><?= utf8_encode(strftime("%A %d %B %G", strtotime($coordinate['date']))); ?></b>?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                <button type="submit" name="delete-coordinate-<?=$coordinate['id']?>" class="btn btn-danger" value="<?=$coordinate['id']?>">Supprimer</button>
                            </div>
                        </div>
                    </div>
                </div>

            <?php endforeach ?>
        </div>
    </form>
<?php else:?>
    <p>Aucune coordonnée pour le moment !</p>
<?php endif;?>
