<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Rame Océan</title>
    <link rel="shortcut icon" type="image/x-icon" href="front/img/favicon.ico">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Rame océan est une association qui propose et organise des traversées océanique à la rame pour toute personne motivée, de l'Atlantique et de la Méditerranée.">

    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://www.rameocean.fr/">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Rame Océan">
    <meta property="og:description" content="Rame océan est une association qui propose et organise des traversées océanique à la rame pour toute personne motivée, de l'Atlantique et de la Méditerranée.">
    <meta property="og:image" content="https://www.rameocean.fr/uploads/rame-ocean-social-card.png">

    <!-- Twitter Meta Tags -->
    <meta property="twitter:url" content="https://www.rameocean.fr/">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Rame Océan">
    <meta property="twitter:domain" content="rameocean.fr">
    <meta name="twitter:description" content="Rame océan est une association qui propose et organise des traversées océanique à la rame pour toute personne motivée, de l'Atlantique et de la Méditerranée.">
    <meta name="twitter:image" content="https://www.rameocean.fr/uploads/rame-ocean-social-card.png">

    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;400;600;700&family=Quicksand:wght@300;400;600&display=swap" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
          integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
          crossorigin=""/>
    <link rel="stylesheet" href="front/css/normalize.css" type="text/css">
    <link rel="stylesheet" href="front/css/style.css" type="text/css">
    <link rel="stylesheet" href="front/css/timeline.css" type="text/css">
    <link rel="stylesheet" href="front/css/gallery.css" type="text/css">

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-NT5BWNJ');
    </script>
    <!-- End Google Tag Manager -->

</head>
<body>

    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NT5BWNJ" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
        <header id="desktopHeader">

        <a href="#carouselExampleCaptions"><img src="front/img/logo_rame_ocean.png" alt="Logo de l'association Rame Océan"></a>
        <nav>
            <?php if($isCurrentVoyage):?>
                <a href="#currentVoyage">Traversée 2023</a>
            <?php endif ?>
            <?php if($isIncoming):?>
                <a href="#incoming">Prochaine traversée</a>
            <?php endif ?>
            <a href="#timeline">Traversées réalisées</a>
            <a href="#partners">Partenaires</a>
            <a href="#gallery">Images</a>
            <a href="#contact">Contact</a>
        </nav>
    </header>

    <nav class="fixedHeader" style="pointer-events: none">
        <?php if($isCurrentVoyage):?>
            <a href="#currentVoyage">Traversée 2023</a>
        <?php endif ?>
        <?php if($isIncoming):?>
            <a href="#incoming">Prochaine traversée</a>
        <?php endif ?>
        <a href="#timeline">Traversées réalisées</a>
        <a href="#partners">Partenaires</a>
        <a href="#gallery">Images</a>
        <a href="#contact">Contact</a>

        <div class="social-media">
            <a href="https://www.facebook.com/rameocean" target="_blank"><i class="icon-facebook"></i></a>
            <a href="https://twitter.com/FavrePatrick" target="_blank"><i class="icon-twitter"></i></a>
            <a href="https://www.instagram.com/rameocean/" target="_blank"><i class="icon-insta"></i></a>
        </div>
    </nav>

    <header id="mobileHeader">
        <div class="waves-container">
            <a href="#carouselExampleCaptions"><img src="front/img/logo_rame_ocean_without_baseline.png" alt="Logo de l'association Rame Océan"></a>
            <nav>
                <?php if($isCurrentVoyage):?>
                    <a href="#currentVoyage">Traversée</a>
                <?php endif ?>
                <?php if($isIncoming):?>
                    <a href="#incoming">Prochaine traversée</a>
                <?php endif ?>
                <a href="#timeline">Traversées réalisées</a>
                <a href="#partners">Partenaires</a>
                <a href="#gallery">Images</a>
                <a href="#contact">Contact</a>
                <div class="social-media">
                    <a href="https://www.facebook.com/rameocean" target="_blank"><i class="icon-facebook"></i></a>
                    <a href="https://twitter.com/FavrePatrick" target="_blank"><i class="icon-twitter"></i></a>
                    <a href="https://www.instagram.com/rameocean/" target="_blank"><i class="icon-insta"></i></a>
                </div>
            </nav>
            <canvas></canvas>
        </div>
    </header>

    <div class="burger">
        <div class="menu-wrapper">
            <div class="line half start"></div>
            <div class="line"></div>
            <div class="line half end"></div>
        </div>
    </div>

    <main>
        <a href="#carouselExampleCaptions" class="arrow-up" style="pointer-events: none">
            <img src="front/img/arrow_up.png" alt="icône pour remonter en haut de la page">
        </a>

        <div id="carouselExampleCaptions" class="carousel slide relative" data-bs-ride="carousel">
            <div class="carousel-indicators absolute right-0 bottom-0 left-0 flex justify-center p-0 mb-4">
                <?php for ($i = 0; $i < count($banners); $i++) {
                    $active = $i === 0 ? 'active' : '' ;
                    $current = $i === 0;
                    $ariaLabel = $i + 1;
                    echo "<button type='button' data-bs-target='#carouselExampleCaptions' data-bs-slide-to='$i' class='$active' aria-current='$current' aria-label='Slide $ariaLabel'></button>";
                } ?>
            </div>

            <div class="carousel-inner relative w-full overflow-hidden">

                <?php foreach($banners as $banner): ?>
                    <figure class="carousel-item <?php echo $banner === $banners[0] ? 'active' : '' ?> relative float-left w-full">
                        <img src="uploads/banner/<?=$banner['picture']?>" class="block w-full" alt="<?=$banner['alt']?>"/>
                        <figcaption class="carousel-caption md:block absolute text-center">
                            <h1 class="mb-0 pb-0"><?=$banner['title']?></h1>
                        </figcaption>
                    </figure>
                <?php endforeach ?>
            </div>

            <!-- BUTTON PREV -->
            <button class="carousel-control-prev absolute top-0 bottom-0 flex items-center justify-center p-0 text-center border-0 hover:outline-none hover:no-underline focus:outline-none focus:no-underline left-0"
                    type="button"
                    data-bs-target="#carouselExampleCaptions"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon inline-block bg-no-repeat" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>

            <!-- BUTTON NEXT -->
            <button class="carousel-control-next absolute top-0 bottom-0 flex items-center justify-center p-0 text-center border-0 hover:outline-none hover:no-underline focus:outline-none focus:no-underline right-0"
                    type="button"
                    data-bs-target="#carouselExampleCaptions"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon inline-block bg-no-repeat" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>

        </div>


        <!-- PreviewImage modal -->
            <!-- Modal -->
            <div class="image-modal-popup">
                <div class="wrapper">
                    <div class="img-and-cross">
                        <span>&times;</span>
                        <img src="" alt="Image Modal">
                    </div>
                </div>
            </div>
        <!-- END PreviewImage modal -->


        <!-- CURRENT VOYAGE -->
        <?php if($isCurrentVoyage):?>

            <section id="currentVoyage" class="nav-container">
                <h1 class="text-marine font-bold uppercase text-center">Traversée 2023</h1>

                <div class="dashboard-wrapper">
                    <div class="voyage-header">
                        <div class="left-side">
                            <button class="btn active" type="button" class="displayNews active" onclick="displayNews()">Newsletter</button>
                        </div>
                        <div class="right-side">
                            <?php foreach($rowers as $rower): ?>
                                <div class="avatar" style="background-image: url('uploads/rower/<?=$rower['picture']?>')"
                                     data-image="<?=$rower['picture']?>"
                                     data-description="<?= htmlspecialchars($rower['description'], ENT_QUOTES); ?>"
                                     onclick="displayRower('<?=$rower['firstname']?> <?=$rower['lastname']?>', '<?=$rower['age']?>', '<?=$rower['job'] ?: ''?>', this)">
                                </div>
                            <?php endforeach ?>
                        </div>
                    </div>

                    <div id="voyage-content">
                        <div class="dynamic-section scrollbar-hidden">
                            <article class="newsletter active">
                                <?php foreach($newsletter as $news): ?>
                                    <div class="resume-item">
                                        <h2><?= utf8_encode(strftime("%A %d %B %G", strtotime($news['date']))); ?></h2>
                                        <div><?=$news['description']?></div>
                                        <?php if($news['picture']):?>
                                            <div class="image-modal-content">
                                                <img class="news-img" src="uploads/newsletter/<?=$news['picture']?>" alt="<?=$news['alt']?>"/>
                                                <div class="backdrop-overlay news-img" data-src="uploads/newsletter/<?=$news['picture']?>"><i class="icon-zoomin" aria-hidden="true"></i></div>
                                            </div>
                                        <?php endif ?>
                                    </div>
                                <?php endforeach ?>
                            </article>
                            <article class="rower-info slide-right">
                                <div class="rower-header">
                                    <figure class="image-modal-content">
                                        <img class="active" src="" alt="" data-bs-target="#staticBackdrop">
                                        <div class="backdrop-overlay" style="border-radius: 50%" data-src=""><i class="icon-zoomin" aria-hidden="true"></i></div>
                                    </figure>
                                    <div>
                                        <h2 class="mb-0"></h2>
                                        <p class="subtitle"><span class="age"></span> ans</p>
                                        <p class="subtitle job"></p>
                                    </div>
                                </div>
                                <div class="rower-description"></div>
                            </article>
                        </div>
                        <div id="map" class="map-desktop"></div>
                    </div>
                </div>
                <?php if($lastAnalytic['picture']):?>
                    <div class="analytics">
                        <div class="analytic-header">
                            <h2>Statistiques</h2>
                            <p class="mb-0"><?= utf8_encode(strftime("%A %d %B %G", strtotime($lastAnalytic['date']))); ?> - <?=$lastAnalytic['hour']?></p>
                        </div>
                        <figure class="image-modal-content">
                            <img class="active" src="uploads/coordinate/<?=$lastAnalytic['picture']?>" alt="">
                        </figure>
                    </div>
                <?php endif ?>

                <div class="crowdfunding-link">
                    <p>Toute l'équipe rame pour Rire Médecin au profit des enfants malades. Soutenez nous, soutenez les. Soyez généreux !</p>
                    <p><small><em>Participez au financement participatif en cliquant ci-dessous</em></small></p>
                    <a href="https://lesdefisdusourire.leriremedecin.org/projects/l-atlantique-a-la-rame-pour-le-rire-medecin" class="bevel-btn" target="_blank">Campagne rire médecin</a>
                </div>

            </section>
        <?php endif ?>

        <!-- INFOS -->
        <div id="infos" class="custom-container">
            <h1 class="mt-6 text-center uppercase logo">Rame <span>océan</span></h1>
            <section id="offers" class="mt-2 text-center">
                <div class="offer">
                    <img src="front/img/rames.png" alt="">
                    <p>Vous prépare pour votre traversée à la rame (solo ou équipage)</p>
                </div>
                <div class="offer">
                    <img src="front/img/prepare.png" alt="">
                    <p>Recherche et prépare votre bateau</p>
                </div>
                <div class="offer">
                    <img src="front/img/skipper.png" alt="">
                    <p>Vous intègre dans un de nos équipages</p>
                </div>
                <div class="offer">
                    <img src="front/img/equipage.png" alt="">
                    <p>Vous prépare mentalement et physiquement</p>
                </div>
                <div class="offer">
                    <img src="front/img/router.png" alt="">
                    <p>Effectue votre routage</p>
                </div>
            </section>

            <?php if($isIncoming):?>
                <a href="#incoming" class="bevel-btn">Découvrez la prochaine traversée !</a>
            <?php endif ?>

        </div>

        <!-- PATRICK -->
        <section id="patrick">
            <div class="darkblue-overlay"></div>
            <div class="custom-container">
                <img src="uploads/profile/<?=$profile['picture']?>" alt="<?=$profile['alt']?>"/>
                <div class="text-white pl-6">
                    <h5 class="text-xl font-medium mb-2 font-bold"><?=$profile['title']?></h5>
                    <div><?=$profile['description']?></div>
                </div>
            </div>
        </section>

        <!-- INCOMING -->
        <?php if($isIncoming):?>
            <section id="incoming" class="custom-container">
                <h1 class="text-marine uppercase font-bold text-center">Prochaine traversée</h1>
                <div class="card">
                    <section class="card-infos">
                        <h2><?=$incoming['title']?></h2>
                        <small><?=$incoming['start_at']?></small>
                        <div class="pills">
                            <p class="pill bg-orange"><span class="number"><?=$incoming['rower']?></span> rameur<?php echo $incoming['rower'] > 1 ? 's' : '' ?></p>
                            <p class="pill bg-blue"><span class="number"><?=$incoming['seat_left']?></span> place<?php echo $incoming['seat_left'] > 1 ? 's' : '' ?> restante<?php echo $incoming['seat_left'] > 1 ? 's' : '' ?></p>
                        </div>
                        <?php if(!$incoming['seat_left']):?>
                            <div class="complete">
                                <p>Il n'y a plus de place pour cette traversée mais nous en organiserons d'autres.</p>
                                <p>N'hésitez pas à nous contacter à l'aide du <a href="#contact">formulaire de contact</a> !</p>
                            </div>
                        <?php else :?>
                            <div><?=$incoming['description']?></div>
                        <?php endif ?>
                    </section>
                    <figure>
                        <img src="uploads/incoming/<?=$incoming['picture']?>" alt="<?=$incoming['alt']?>">
                    </figure>
                </div>
            </section>
        <?php endif ?>


        <!-- TIMELINE -->
        <section id="timeline">

            <h1 class="text-marine uppercase font-bold text-center">Traversées réalisées</h1>
            <small>Cliquez sur une année pour plus d'infos !</small>

            <div class="flex-parent">
                <div class="dot-flex-container">
                    <?php foreach($trips as $trip): ?>
                        <div class="dot <?php echo $trip === $trips[0] ? 'active' : '' ?>">
                            <span data-year="<?=$trip['date']?>" data-info="<?=$trip['title']?>"></span>
                        </div>
                    <?php endforeach ?>
                </div>

                <div class="description-flex-container">

                    <?php foreach($trips as $trip): ?>
                        <article class="<?php echo $trip === $trips[0] ? 'active' : '' ?>">
                            <?php if($trip['is_video']):?>
                                <div class="text no-picture">
                                    <iframe width="560" height="315" src="https://www.youtube.com/embed/<?=$trip['video_url']?>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                    <h5><?php echo $trip['subtitle'] ? $trip['subtitle'] : $trip['title'] ?></h5>
                                    <div><?=$trip['description']?></div>
                                </div>
                            <?php else :?>
                                <?php if($trip['picture']):?>
                                    <div class="media">
                                        <img src="uploads/trip/<?=$trip['picture']?>" alt="">
                                    </div>
                                <?php endif ?>
                                <div class="text">
                                    <h5><?php echo $trip['subtitle'] ? $trip['subtitle'] : $trip['title'] ?></h5>
                                    <div><?=$trip['description']?></div>
                                </div>
                            <?php endif ?>
                        </article>
                    <?php endforeach ?>

                </div>
            </div>

        </section>

        <!-- PARTENAIRE -->
        <section id="partners">
            <h1 class="text-white uppercase font-bold text-center">Partenaires</h1>
            <div class="custom-container">
                <div class="btn-and-partners">
                    <div class="partners-btn">
                        <?php if($mainPartners):?>
                            <button type="button" class="blue-btn displayNews active" onclick="displayPartners('partner-<?=$partnerRepo::PARTNER_MAIN?>', this)"><?=$partnerCategories[$partnerRepo::PARTNER_MAIN]?></button>
                        <?php endif ?>
                        <?php if($officialPartners):?>
                            <button type="button" class="blue-btn displayNews" onclick="displayPartners('partner-<?=$partnerRepo::PARTNER_OFFICIAL?>', this)"><?=$partnerCategories[$partnerRepo::PARTNER_OFFICIAL]?></button>
                        <?php endif ?>
                        <?php if($institutionalPartners):?>
                            <button type="button" class="blue-btn displayNews" onclick="displayPartners('partner-<?=$partnerRepo::PARTNER_INSTITUTIONAL?>', this)"><?=$partnerCategories[$partnerRepo::PARTNER_INSTITUTIONAL]?></button>
                        <?php endif ?>
                        <?php if($technicPartners):?>
                            <button type="button" class="blue-btn displayNews" onclick="displayPartners('partner-<?=$partnerRepo::PARTNER_TECHNIC?>', this)"><?=$partnerCategories[$partnerRepo::PARTNER_TECHNIC]?></button>
                        <?php endif ?>
                    </div>
                    <div class="partners">
                        <!-- MAIN PARTNERS -->
                        <?php if($mainPartners):?>
                            <div class="category-partner active" id="partner-<?=$partnerRepo::PARTNER_MAIN?>">
                                <?php foreach($mainPartners as $mainPartner): ?>
                                    <figure>
                                        <figcaption><?=$mainPartner['title']?></figcaption>
                                        <img src="uploads/partner/<?= $mainPartner['picture'] ?>" alt="<?= $mainPartner['alt'] ?>">
                                    </figure>
                                <?php endforeach ?>
                            </div>
                        <?php endif ?>

                        <!-- OFFICIAL PARTNERS -->
                        <?php if($officialPartners):?>
                            <div class="category-partner slide-left" id="partner-<?=$partnerRepo::PARTNER_OFFICIAL?>">
                                <?php foreach($officialPartners as $officialPartner): ?>
                                    <figure>
                                        <figcaption><?=$officialPartner['title']?></figcaption>
                                        <img src="uploads/partner/<?= $officialPartner['picture'] ?>" alt="<?= $officialPartner['alt'] ?>">
                                    </figure>
                                <?php endforeach ?>
                            </div>
                        <?php endif ?>

                        <!-- INSTITUTIONAL PARTNERS -->
                        <?php if($institutionalPartners):?>
                            <div class="category-partner slide-left" id="partner-<?=$partnerRepo::PARTNER_INSTITUTIONAL?>">
                                <?php foreach($institutionalPartners as $institutionalPartner): ?>
                                    <figure>
                                        <figcaption><?=$institutionalPartner['title']?></figcaption>
                                        <img src="uploads/partner/<?= $institutionalPartner['picture'] ?>" alt="<?= $institutionalPartner['alt'] ?>">
                                    </figure>
                                <?php endforeach ?>
                            </div>
                        <?php endif ?>

                        <!-- TECHNICAL PARTNERS -->
                        <?php if($technicPartners):?>
                            <div class="category-partner slide-left" id="partner-<?=$partnerRepo::PARTNER_TECHNIC?>">
                                <?php foreach($technicPartners as $technicPartner): ?>
                                    <figure>
                                        <figcaption><?=$technicPartner['title']?></figcaption>
                                        <img src="uploads/partner/<?= $technicPartner['picture'] ?>" alt="<?= $technicPartner['alt'] ?>">
                                    </figure>
                                <?php endforeach ?>
                            </div>
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </section>

        <!-- GALLERY -->
        <section id="gallery">

            <h1 class="text-marine uppercase font-bold text-center">Galerie photo</h1>

            <div id="image-gallery" class="grid grid-cols-8 md-grid-cols-3 gap-4">
                <?php foreach($gallery as $picture): ?>
                    <div class="image">
                        <figure class="img-wrapper">
                            <img class="img-responsive" src="uploads/gallery/<?= $picture['picture'] ?>" alt="<?= $picture['alt'] ?>">
                            <figcaption class="img-overlay">
                                <h3 class="fw-bold text-uppercase mb-3" data-title="<?= $picture['title'] ?>" data-credit="<?= $picture['credit'] ?>"><?= $picture['title'] ?></h3>
                                <i class="icon-zoomin" aria-hidden="true"></i>
                            </figcaption>
                        </figure>
                    </div>
                <?php endforeach ?>
            </div><!-- End image gallery -->
        </section>

        <section id="contact">
            <div class="darkblue-overlay"></div>
            <div class="form-container">
                <h1 class="text-white uppercase font-bold text-center">Contact</h1>
                <form method="post">

                    <div class="form-group w-33 sm-w-100">
                        <label for="firstname">Prénom</label>
                        <input type="text" id="firstname" name="firstname"
                               class="rounded-none rounded-lg bg-gray-50 border border-gray-300 text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                               placeholder="Jacques-Yves">
                    </div>

                    <div class="form-group w-33 sm-w-100">
                        <label for="lastname">Nom</label>
                        <input type="text" id="lastname" name="lastname"
                               class="rounded-none rounded-lg bg-gray-50 border border-gray-300 text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                               placeholder="Cousteau">
                    </div>

                    <div class="form-group w-33 sm-w-100 phone">
                        <label for="phone">Téléphone</label>
                        <div class="flex">
                            <input type="tel" id="phone" name="phone" onchange="removeError(document.querySelector('.phone .flex'))"
                                   class="rounded-none rounded-lg bg-gray-50 border border-gray-300 text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                   placeholder="06 00 00 00 00">
                        </div>
                    </div>

                    <div class="form-group w-50 sm-w-100">
                        <label for="email" class="">Mail</label>
                        <input type="email" id="email" name="email"
                               class="rounded-none rounded-lg bg-gray-50 border border-gray-300 text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                               placeholder="mrcousteau@mail.com">
                    </div>

                    <div class="form-group w-50 sm-w-100">
                        <label for="demand">Votre demande</label>
                        <select id="demand" name="demand" onchange="removeError(this)"
                                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                            <option value="1">Sélectionnez un choix</option>
                            <option value="traversee solo">Réaliser une traversée en solo</option>
                            <option value="traversee equipage">Réaliser une traversée en équipage</option>
                            <option value="logistique">Demande de logistique</option>
                            <option value="routage">Demande de routage</option>
                        </select>
                    </div>

                    <div class="form-group w-100">
                        <label for="content">Votre message</label>
                        <textarea id="content" name="content" rows="4" onchange="removeError(this)"
                                  class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Formulez votre demande"></textarea>
                    </div>

                    <button class="btn">Envoyer</button>

                </form>
            </div>

        </section>

    </main>

    <!-- JS TAILWIND -->
    <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>
    <!-- JS LEAFLET -->
    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
    <!-- MAP -->
    <script>
        let isMobile = false;

        if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){
            isMobile = true
        }
        else{
            isMobile = false
        }

        // if ("maxTouchPoints" in navigator) {
        //     hasTouchScreen = navigator.maxTouchPoints > 0;
        // } else if ("msMaxTouchPoints" in navigator) {
        //     hasTouchScreen = navigator.msMaxTouchPoints > 0;
        // } else {
        //     let mQ = window.matchMedia && matchMedia("(pointer:coarse)");
        //     if (mQ && mQ.media === "(pointer:coarse)") {
        //         hasTouchScreen = !!mQ.matches;
        //     } else if ('orientation' in window) {
        //         hasTouchScreen = true; // deprecated, but good fallback
        //     } else {
        //         // Only as a last resort, fall back to user agent sniffing
        //         let UA = navigator.userAgent;
        //         hasTouchScreen = (
        //             /\b(BlackBerry|webOS|iPhone|IEMobile)\b/i.test(UA) ||
        //             /\b(Android|Windows Phone|iPad|iPod)\b/i.test(UA)
        //         );
        //     }
        // }

        if(isMobile) {
            // mobile stuff
            const dashWrap = document.querySelector('.dashboard-wrapper');
            const voyageHeader = document.querySelector('.voyage-header');
            const mapDiv = document.getElementById('map');
            const analyticsDiv = document.querySelector('.analytics');
            dashWrap.insertBefore(mapDiv, voyageHeader);
            if(analyticsDiv) {
                dashWrap.insertBefore(analyticsDiv, voyageHeader);
            }
            mapDiv.classList.remove('map-desktop');
            mapDiv.classList.add('map-mobile');
        }

        let map = L.map('map').setView([30.998911, -33.566280], 4);

        L.tileLayer('https://tile.thunderforest.com/transport-dark/{z}/{x}/{y}.png?apikey=2d32a4cc5e12405ab5cfc6c0eb84266d', {
            maxZoom: 19,
            type: 'normal',
            format: 'png',
            attribution: '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        const pointsForJson  = [];

        let rowerIcon = new L.Icon({
            iconUrl: 'https://www.rameocean.fr/front/img/rower-icon.png',
            iconSize: [35, 30],
            iconAnchor: [10, 30],
            popupAnchor: [1, -34],
            shadowSize: [41, 41]
        });

         // Markers
        let popupHtml = `<h6>Point de départ</h6>`
        L.marker([<?=$voyage['latitude']?>, <?=$voyage['longitude']?>]).bindPopup(popupHtml).addTo(map).on('click', onPinClick)
        <?php foreach($coordinates as $coordinate): ?>
            pointsForJson .push([<?=$coordinate['longitude']?>, <?=$coordinate['latitude']?>])
            popupHtml = `<h2><?= utf8_encode(strftime("%A %d %B %G", strtotime($coordinate['date']))); ?></h2><p><?=$coordinate['hour']?></p>`
            L.marker([<?=$coordinate['latitude']?>, <?=$coordinate['longitude']?>], {icon: rowerIcon}).bindPopup(popupHtml).addTo(map).on('click', onPinClick)
        <?php endforeach ?>
        pointsForJson .push([<?=$voyage['longitude']?>, <?=$voyage['latitude']?>])

        var polyline = L.polyline(lngLatArrayToLatLng(pointsForJson), {
            color: 'white',
            weight: 2,
            smoothFactor: -1
        }).addTo(map);
        map.fitBounds(polyline.getBounds());

        function lngLatArrayToLatLng(lngLatArray) {
            return lngLatArray.map(lngLatToLatLng);
        }

        function lngLatToLatLng(lngLat) {
            return [lngLat[1], lngLat[0]];
        }

        function onPinClick() {
            console.log('Hello');
        }
    </script>
    <!-- END MAP -->

    <!-- jQUERY -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Custom JS -->
    <script src="front/js/script.js"></script>
    <script src="front/js/movingWaves.js"></script>
    <script src="front/js/gallery.js"></script>

    <script>
        window.axeptioSettings = {
            clientId: "6396df5a0086644314b5c087",
            cookiesVersion: "rameocean-fr",
        };

        (function(d, s) {
            var t = d.getElementsByTagName(s)[0], e = d.createElement(s);
            e.async = true; e.src = "//static.axept.io/sdk.js";
            t.parentNode.insertBefore(e, t);
        })(document, "script");
    </script>
</body>

</html>
