<a href="index.php?name=addGallery" class="btn btn-outline-blue mb-3"><i class="fas fa-plus pr-1"></i> Ajouter une photo à la galerie</a>

<form action ="" method="POST">
    <div class="row ml-0 d-flex justify-content-xl-start justify-content-center mt-4">
        <?php foreach($vars['gallery'] as $gallery): ?>

            <div class="mr-4 mb-4 position-relative" style="box-shadow: 0px 2px 17px -6px rgba(0,0,0,0.75);">
                <div class="position-absolute" style="z-index:1;">
                    <a href="#" data-toggle="modal" data-target="#gallery-<?=$gallery['id']?>" class="btn btn-danger"><i class="fas fa-window-close"></i></a>
                </div>
                <div class="position-absolute" style="z-index:1;right: 0">
                    <a href="index.php?name=addGallery&id=<?=$gallery['id'] ?>" class="btn btn-primary"><i class="fas fa-pencil-alt"></i></a>
                </div>
                <div class="card card-list card-gallery">
                    <img src="../uploads/gallery/<?=$gallery['picture'] ?>" class="d-block w-100">
                </div>
            </div>

            <!-- Modal de suppression -->
            <?php if($_SESSION['user']['role'] !== 'ROLE_ADMIN') :?>
                <div class="modal fade" id="gallery-<?=$gallery['id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="exampleModalLabel">Désolé...</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Vous n'avez <b>pas les droits</b> pour supprimer une photo de bannière.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php else :?>
                <div class="modal fade" id="gallery-<?=$gallery['id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="exampleModalLabel">Attention</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Êtes-vous sûr de vouloir supprimer la photo <b><?=$gallery['title']?></b>?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                <input type="hidden" name="title-<?=$gallery['id']?>" value="<?=$gallery['title']?>"/>
                                <input type="hidden" name="picture-<?=$gallery['id']?>" value="<?=$gallery['picture']?>"/>
                                <button type="submit" name="delete-picture-<?=$gallery['id']?>" class="btn btn-danger" value="<?=$gallery['id']?>">Supprimer</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif ;?>
        <?php endforeach ?>
    </div>
</form>
