<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rame Océan Admin</title>
    <link rel="shortcut icon" type="image/x-icon" href="../front/img/favicon.ico">
    <!-- FONT AWESOME -->
    <script src="https://kit.fontawesome.com/73ab01ebea.js" crossorigin="anonymous"></script>
    <!-- BOOTSTRAP CSS -->
    <link href="assets\css\style.min.css" rel="stylesheet" type="text/css">
    <link href="assets\css\custom.css" rel="stylesheet" type="text/css">
    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;400;600;700&family=Quicksand:wght@300;400;600&display=swap" rel="stylesheet">
    <!-- TINY MCE JAVASCRIPT -->
    <script src="assets\js\tinymce\tinymce.min.js"></script>
</head>

<body>
<!-- ============================================================== -->
<!-- Preloader - style you can find in spinners.css -->
<!-- ============================================================== -->
<div class="preloader">
    <div class="lds-ripple">
        <div class="lds-pos"></div>
        <div class="lds-pos"></div>
    </div>
</div>
<!-- ============================================================== -->
<!-- Main wrapper - style you can find in pages.scss -->
<!-- ============================================================== -->
<div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
     data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <header class="topbar" data-navbarbg="skin5">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
            <div class="navbar-header" data-logobg="skin6">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <a class="logo text-dark h4 pl-4 pr-2" href="index.php">
                    <b>RAME</b> OCEAN
                </a>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- toggle and nav items -->
                <!-- ============================================================== -->
                <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
                   href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            </div>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                <ul class="navbar-nav d-none d-md-block d-lg-none">
                    <li class="nav-item">
                        <a class="nav-toggler nav-link waves-effect waves-light text-white"
                           href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                    </li>
                </ul>
                <!-- ============================================================== -->
                <!-- Right side toggle and nav items -->
                <!-- ============================================================== -->
                <ul class="navbar-nav ml-auto d-flex align-items-center">
                    <!-- ============================================================== -->
                    <li>
                        <a class="profile-pic mr-3" href="#">
                            <img src="assets\img\default-avatar-white.svg" alt="user-img" width="45" height="45" class="img-circle">
                            <span class="text-white font-bold font-16"><?= $_SESSION['user']['firstname'] ?></span>
                        </a>
                    </li>
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                </ul>
            </div>
        </nav>
    </header>
    <!-- ============================================================== -->
    <!-- End Topbar header -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <aside class="left-sidebar" data-sidebarbg="skin6" >
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <!-- DASHBOARD -->
                    <li class="sidebar-item ">
                        <a class="sidebar-link waves-effect waves-dark" href="index.php" aria-expanded="false">
                            <i class="fas fa-clock fa-fw" aria-hidden="true"></i><span class="hide-menu">Dashboard</span>
                        </a>
                    </li>

                    <!-- BANNER -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark" href="index.php?name=banners" aria-expanded="false">
                            <i class="fa fa-images" aria-hidden="true"></i><span class="hide-menu">Bannière</span>
                        </a>
                    </li>
                    <!-- ADD BANNER -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark py-2 text-muted" href="index.php?name=addBanner" aria-expanded="false">
                            <span class="hide-menu pl-2"><i class="fa fa-plus text-muted" aria-hidden="true"></i>Ajouter une photo</span>
                        </a>
                    </li>

                    <!-- PROFILE -->
                    <li class="sidebar-item ">
                        <a class="sidebar-link waves-effect waves-dark" href="index.php?name=profile" aria-expanded="false">
                            <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i><span class="hide-menu">Biographie</span>
                        </a>
                    </li>

                    <!-- INCOMING -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark" href="index.php?name=incoming" aria-expanded="false">
                            <i class="fa fa-clock" aria-hidden="true"></i><span class="hide-menu">Prochaine traversée</span>
                        </a>
                    </li>

                    <!-- TRIP -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark" href="index.php?name=trips" aria-expanded="false">
                            <i class="fa fa-anchor" aria-hidden="true"></i><span class="hide-menu">Traversées réalisées</span>
                        </a>
                    </li>
                    <!-- ADD TRIP -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark py-2 text-muted" href="index.php?name=addTrip" aria-expanded="false">
                            <span class="hide-menu pl-2"><i class="fa fa-plus text-muted" aria-hidden="true"></i>Ajouter une traversée</span>
                        </a>
                    </li>

                    <!-- PARTNER -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark" href="index.php?name=partners" aria-expanded="false">
                            <i class="fa fa-briefcase" aria-hidden="true"></i><span class="hide-menu">Partenaires</span>
                        </a>
                    </li>
                    <!-- ADD PARTNER -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark py-2 text-muted" href="index.php?name=addPartner" aria-expanded="false">
                            <span class="hide-menu pl-2"><i class="fa fa-plus text-muted" aria-hidden="true"></i>Ajouter un partnaire</span>
                        </a>
                    </li>


                    <!-- GALLERY -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark" href="index.php?name=gallery" aria-expanded="false">
                            <i class="fa fa-camera" aria-hidden="true"></i><span class="hide-menu">Galerie Photo</span>
                        </a>
                    </li>
                    <!-- ADD GALLERY -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark py-2 text-muted" href="index.php?name=addGallery" aria-expanded="false">
                            <span class="hide-menu pl-2"><i class="fa fa-plus text-muted" aria-hidden="true"></i>Ajouter une photo</span>
                        </a>
                    </li>

                    <!-- USERS -->
                    <li class="sidebar-item">
                        <a class="sidebar-link waves-effect waves-dark" href="index.php?name=users" aria-expanded="false">
                            <i class="fa fa-users" aria-hidden="true"></i><span class="hide-menu">Utilisateurs</span></a>
                    </li>
                    <!-- ADD USER -->
                    <li class="sidebar-item ">
                        <a class="sidebar-link waves-effect waves-dark py-2 text-muted" href="index.php?name=addUser" aria-expanded="false">
                            <span class="hide-menu pl-2"><i class="fa fa-plus text-muted" aria-hidden="true"></i>Ajouter un utilisateur</span>
                        </a>
                    </li>
                </ul>

            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
    </aside>
    <!-- ============================================================== -->
    <!-- End Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Page wrapper  -->
    <!-- ============================================================== -->
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center pb-1">
                <div class="col-lg-10 col-md-4 col-sm-7 col-xs-12">
                    <h4 class="page-title text-uppercase font-medium"><?=$titlePage?></h4>
                </div>
                <div class="col-lg-2 col-sm-5 col-md-8 col-xs-12">

                    <div class="d-sm-flex">
                        <ol class="breadcrumb ml-auto">
                            <li><a href="logout.php"></a></li>
                        </ol>
                        <i class="fa fa-power-off pr-1 float-end" style="margin-top: 2px;"></i><a href="index.php?name=logout" class="text-dark">Déconnexion</a>
                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">

            <?php if (isset($flashBag) && $flashBag) :?>
                <?php foreach ($flashBag as $message) :?>
                    <div class="alert alert-dismissible alert-<?= $message['level'] ?>" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <p><?= $message['message'] ?></p>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php
                include($view.'.phtml');
            ?>
        </div>
    </div>
</div>

<!-- Option 1: jQuery and Bootstrap Bundle -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="assets\plugins\bower_components\popper.js\dist\popper.min.js"></script>
<script src="assets\bootstrap/dist\js/bootstrap.min.js"></script>
<!--Menu sidebar -->
<script src="assets\js\sidebarmenu.js"></script>
<!--Custom JavaScript -->
<script src="assets\js\uploader.js"></script>
<script src="assets\js\custom.js"></script>

<script>
    tinymce.init({
        selector: 'textarea',
        height: 300,
        relative_urls: false,
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table paste imagetools wordcount",
            'image code'
        ],
        toolbar: "insertfile undo redo | image code | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
        content_css: [
            'bootstrap/dist/css/bootstrap.min.css',
            'css/editor.css'
        ]
    });
</script>

</body>
</html>
