<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/x-icon" href="../front/img/favicon.ico">
    <script src="https://kit.fontawesome.com/73ab01ebea.js" crossorigin="anonymous"></script>
    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;400;600;700&family=Quicksand:wght@300;400;600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css" />
    <link rel="stylesheet" href="assets/css/login.css">

    <title>Login</title>
</head>
<body>

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-darkblue text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <form method="POST">
                            <div class="mb-0 mt-md-4 pb-5">

                                <h1 class="logo">Rame <span>océan</span></h1>
                                <p class="text-white-50 mb-5">Formulaire de connexion</p>

                                <div class="form-outline form-white mb-4">
                                    <input type="email" id="email" class="form-control form-control-lg" value="<?=$email?>" name="email"/>
                                    <label class="form-label" for="email">Email</label>
                                </div>

                                <div class="form-outline form-white mb-4">
                                    <input type="password" id="password" class="form-control form-control-lg" name="password"/>
                                    <label class="form-label" for="password">Mot de passe</label>
                                </div>

                                <?php if($error) :?><p class="text-danger mb-2">Identifiants incorrects</p><?php endif;?>
                                <?php if($mailError) :?><p class="text-danger mb-2">Email introuvable en base</p><?php endif;?>
                                <?php if($displayConfirmation) :?><p class="text-success mb-2 fw-bold">Email envoyé</p><?php endif;?>

                                <a class="small mb-5 pb-lg-2 text-white-50" data-mdb-target="#updatePassword" data-mdb-toggle="modal">Mot de passe oublié ?</a>

                                <button class="custom-btn" type="submit" name="connexion">Envoyer</button>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal -->
<form method="POST">
    <div class="modal fade" id="updatePassword" tabindex="-1" aria-labelledby="updatePassword" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content p-6">
                <div class="modal-header bg-danger text-white">
                    <h5 class="modal-title fw-bold text-uppercase" id="exampleModalLabel">Réinitialisation du mot de passe</h5>
                    <button type="button" class="cross-btn text-white" data-mdb-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
                </div>
                <div class="modal-body">
                    <p>Tu es sur le point de <b>réinitialiser ton mot de passe</b>.</p>
                    <p>Si c'est ce que tu veux faire dans ce cas :</p>
                    <br>

                    <p><span class="number">1</span> Renseigne ton mail de connexion habituel.</p>
                    <p><span class="number">2</span> Tu recevras un mail. Check bien dans toutes les boîtes.</p>
                    <p><span class="number">3</span> Ce mail te donnera accès à une page pour <b>modifier</b> ton mot de passe.</p>

                    <div class="form-outline mb-4">
                        <input type="email" id="mailTo" class="form-control form-control-lg" value="<?=$mailTo?>" name="mailTo"/>
                        <label class="form-label" for="mailTo">Email</label>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Annuler</button>
                    <button type="submit" class="btn btn-primary" name="updatePassword">Envoyer</button>
                </div>
            </div>
        </div>
    </div>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js" type="text/javascript"></script>

</body>
</html>
