<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/x-icon" href="../front/img/rame-ocean-favicon.png">

    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;400;600;700&family=Quicksand:wght@300;400;600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.css" />
    <link rel="stylesheet" href="assets/css/login.css">

    <title>Reset Password</title>
</head>
<body>

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-darkblue text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <form method="POST">
                            <div class="mb-0 mt-md-4 d-flex justify-content-center flex-column">

                                <input type="hidden" name="token" value="<?=$_SESSION['token']?>">

                                <?php if($tokenError) :?>

                                    <h1 class="text-danger text-center w-100 mt-3">Mauvais lien.</h1>
                                    <p class="text-center w-100 mt-3">Utilises le <b>dernier lien reçu</b> dans tes mails !</p>

                                <?php else :?>

                                    <?php if($displayConfirmation) :?>
                                        <p class="text-success text-center w-100 mt-3 h4"><i class="fas fa-check pr-1"></i> Mot de passe mis à jour !</p>
                                        <div class="d-flex justify-content-center mb-3"><a class="custom-btn" href="login.php">Accéder au login</a></div>
                                    <?php else :?>
                                        <h1 class="logo">Rame <span>océan</span></h1>
                                        <p class="text-white-50 mb-5">Réinitialisation du mot de passe</p>

                                        <div class="form-outline form-white mb-4">
                                            <input type="email" id="email" class="form-control form-control-lg" value="<?php if(isset($_SESSION['userMail'])) :?><?=$_SESSION['userMail']?><?php endif;?>" name="email"/>
                                            <label class="form-label" for="email">Email</label>
                                        </div>

                                        <div class="form-outline form-white mb-4">
                                            <input type="password" id="password" class="form-control form-control-lg" name="password"/>
                                            <label class="form-label" for="password">Mot de passe</label>
                                        </div>

                                        <div class="form-outline form-white mb-4">
                                            <input type="confirmPassword" id="password" class="form-control form-control-lg" name="confirmPassword"/>
                                            <label class="form-label" for="confirmPassword">Confirmation du mot de passe</label>
                                        </div>

                                        <?php if(isset($errors['email'])) :?><p class="text-danger mb-2"><?=$errors['email']?></p><?php endif;?>
                                        <?php if(isset($errors['confirmPassword'])) :?><p class="text-danger mb-2"><?=$errors['confirmPassword']?></p><?php endif;?>
                                    <?php endif;?>

                                    <button class="custom-btn" type="submit" name="update">Envoyer</button>

                                <?php endif;?>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.2.0/mdb.min.js" type="text/javascript"></script>

</body>
</html>
