
<form action="" id="file-upload-form" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
    <div class="row">
        <div class="col-lg-4 col-xlg-3 col-md-12">
            <label class="col-md-12 pl-0 h3 text-primary text-center mb-2 pr-0" for="picture">Photo</label>
            <div class="parent-div d-flex justify-content-center position-relative">
                <input type="file" name="picture" id="file-upload" class="pointer" data-max-files="1" style="position:absolute;top:0;left:0;opacity:0"/>
                <span id="file-upload-btn" class="btn btn-primary"><i class="fa fa-download text-white pr-2" aria-hidden="true"></i>Drag or clic</span>
            </div>
            <div class="form-group col-md-12 py-2 mb-0">
                <label for="file-upload" id="file-drag" class="d-flex justify-content-center">
                    <!-- EDITION : si on a une photo on l'affiche et on passe le nom de cette photo dans un champ caché ! -->
                    <?php if($vars['oldPicture'] !== null) :?>
                        <input type="hidden" name="oldPicture" value="<?=$vars['oldPicture']?>">
                        <img id="file-image" src="../uploads/incoming/<?=$vars['oldPicture']?>" class="hidden pt-2 d-block m-auto">
                    <?php else:?>
                        <img id="file-image" src="assets\img\download-icon.png" class="hidden pt-2 d-block m-auto">
                    <?php endif;?>
                    <div class="position-relative">
                        <div id="start" style="left: 0; top: 0; opacity: 0; position: absolute;">
                            <i class="fa fa-download" aria-hidden="true"></i>
                            <div></div>
                            <span id="file-upload-btn" class="btn btn-primary"></span>
                            <div id="notimage" class="hidden"></div>
                        </div>
                        <div id="response" class="hidden" style="opacity:0;display:none">
                            <div id="messages"></div>
                            <progress class="progress" id="file-progress" value="0">
                                <span>0</span>%
                            </progress>
                        </div>
                </label>
            </div>
        </div>
        <div class="parent-div d-flex justify-content-center flex-wrap">
            <p class="form-text text-center">Pour modifier une image téléchargez en une nouvelle. Sinon l'ancienne sera conservée !</p>
            <p class="text-secondary text-center">Taille max : <b>2 Mo</b></p>
            <?php if(!empty($vars['errors']) && isset($vars['errors']['picture'])):?>
                <p class="text-danger mb-0"><?=$vars['errors']['picture']?></p>
            <?php endif ?>
        </div>
    </div>

    <div class="col-lg-8 col-xlg-9 col-md-12" id="incoming">
        <div class="card">
            <div class="card-body">

                <div class="input-switch">
                    <label for="is_active">Off</label>
                    <input type="checkbox" id="is_active" name="is_active" class="input" <?php if($vars['is_active']) :?>checked<?php endif; ?>/>
                    <label for="is_active" class="switch"></label>
                    <label for="is_active">On</label>
                </div>

                <!-- DATE -->
                <div class="form-group col-md-6 mb-4">
                    <label>Date de départ</label>
                    <div class="col-md-12 border-bottom p-0">
                        <input type="text" name="start_at" value="<?=$vars['start_at']?>" class="form-control p-0 border-0">
                    </div>
                    <?php if(!empty($vars['errors']) && isset($vars['errors']['start_at'])):?>
                        <p class="text-danger mb-0 pt-1"><?=$vars['errors']['start_at']?></p>
                    <?php endif ?>
                </div>

                <div class="col-md-12 d-flex flex-wrap">
                    <!-- ROWERS -->
                    <div class="form-group mb-4 mr-5">
                        <label>Rameurs</label>
                        <div class="col-md-6 p-0">
                            <div class="value pl-3" id="rower">0</div>
                            <input type="range" min="0" max="10" step="1" name="rower" class="form-control-range" value="<?=$vars['rower']?>" oninput="rangeValue(this, '#rower')">
                        </div>
                        <?php if(!empty($vars['errors']) && isset($vars['errors']['rower'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['rower']?></p>
                        <?php endif ?>
                    </div>

                    <!-- SEAT -->
                    <div class="form-group mb-4">
                        <label>Places restantes</label>
                        <div class="col-md-6 border-bottom p-0">
                            <div class="value" id="seat_left">0</div>
                            <input type="range" min="0" max="10" step="1" name="seat_left" class="form-control-range" value="<?=$vars['seat_left']?>" oninput="rangeValue(this, '#seat_left')">
                        </div>
                        <?php if(!empty($vars['errors']) && isset($vars['errors']['seat_left'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['seat_left']?></p>
                        <?php endif ?>
                    </div>
                </div>


                <!-- TITLE -->
                <div class="form-group col-md-6 mb-4">
                    <label>Titre</label>
                    <div class="col-md-12 border-bottom p-0">
                        <input type="text" name="title" value="<?=$vars['title']?>" class="form-control p-0 border-0">
                    </div>
                    <?php if(!empty($vars['errors']) && isset($vars['errors']['title'])):?>
                        <p class="text-danger mb-0 pt-1"><?=$vars['errors']['title']?></p>
                    <?php endif ?>
                </div>

                <!-- ALT -->
                <div class="form-group col-md-6 mb-4">
                    <label>Alt</label>
                    <div class="col-md-12 border-bottom p-0">
                        <input type="text" name="alt" value="<?=$vars['alt']?>" class="form-control p-0 border-0">
                    </div>
                    <small class="text-secondary">Le <b>alt</b> sert à l'audio-description des images pour les non-voyants.</small>
                    <?php if(!empty($vars['errors']) && isset($vars['errors']['alt'])):?>
                        <p class="text-danger mb-0 pt-1"><?=$vars['errors']['alt']?></p>
                    <?php endif ?>
                </div>

                <!-- DESCRIPTION -->
                <div class="form-group col-md-12 pb-4 mb-0">
                    <label for="description">Texte de présentation</label>
                    <div class="col-md-12 border-bottom p-0">
                        <textarea class="form-control" name ="description" id="description" rows="6" style="height: 300px;"><?=$vars['description']?></textarea>
                    </div>
                    <?php if(!empty($vars['errors']) && isset($vars['errors']['description'])):?>
                        <p class="text-danger mb-0 pt-1"><?=$vars['errors']['description']?></p>
                    <?php endif ?>
                </div>


            </div>
        </div>
    </div>
    <div class="col-lg-4 col-xlg-3 col-md-12"></div>
    <div class="col-lg-8 col-xlg-9 col-md-12">
        <button type="submit" class="btn btn-success text-white mt-3"><i class="fas fa-check pr-1"></i><?php echo $vars['id'] ? 'MODIFIER' : 'CREER' ?></button>
    </div>
</form>
