
<a href="index.php?name=banners" class="btn btn-secondary mb-3"><i class="fas fa-arrow-alt-circle-left pr-1"></i>Annuler</a>

<div id="drop-area" class="flex-wrap">
    <form method="POST" enctype="multipart/form-data" class="form-horizontal form-material">

        <!-- PHOTO -->
        <div class="form-group col-md-12 no-gutters">

            <label class="col-md-12 pl-0 h3 text-primary text-center mb-2 pr-0" for="picture">Photo</label>
            <div class="parent-div d-flex justify-content-center position-relative">
                <input type="file" name="picture" id="file-upload" class="pointer" data-max-files="1" style="position:absolute;top:0;left:0;opacity:0"/>
                <span id="file-upload-btn" class="btn btn-primary"><i class="fa fa-download text-white pr-2" aria-hidden="true"></i>Drag or clic</span>
            </div>
            <div class="form-group col-md-12 py-2 mb-0">
                <p class="text-secondary text-center">Dimensions conseillées : <b>1920x740 px</b>. Taille max : <b>2 Mo</b></p>
                <label for="file-upload" id="file-drag" class="d-flex justify-content-center">
                    <!-- EDITION : si on a une photo on l'affiche et on passe le nom de cette photo dans un champ caché ! -->
                    <?php if($vars['oldPicture'] !== null) :?>
                        <input type="hidden" name="oldPicture" value="<?=$vars['oldPicture']?>">
                        <img id="file-image" src="../uploads/banner/<?=$vars['oldPicture']?>" class="hidden pt-2 d-block m-auto">
                    <?php else:?>
                        <img id="file-image" src="assets\img\download-icon.png" class="hidden pt-2 d-block m-auto">
                    <?php endif;?>
                    <div class="position-relative">
                        <div id="start" style="left: 0; top: 0; opacity: 0; position: absolute;">
                            <i class="fa fa-download" aria-hidden="true"></i>
                            <div></div>
                            <span id="file-upload-btn" class="btn btn-primary"></span>
                            <div id="notimage" class="hidden"></div>
                        </div>
                        <div id="response" class="hidden" style="opacity:0;display:none">
                            <div id="messages"></div>
                            <progress class="progress" id="file-progress" value="0">
                                <span>0</span>%
                            </progress>
                        </div>
                </label>
            </div>
        </div>
        <div class="parent-div d-flex justify-content-center flex-wrap">
            <?php if(!empty($vars['errors']) && isset($vars['errors']['picture'])):?>
                <p class="text-danger mb-0"><?=$vars['errors']['picture']?></p>
            <?php endif ?>
        </div>

</div>

<!-- TITRE -->
<div class="d-flex col-md-12 no-gutters flex-wrap">
    <div class="form-group col-lg-4 pb-1 add-picture-input-title">
        <label for="title">Titre</label>
        <div class="border-bottom p-0">
            <input type="text" name="title" id="title" value="<?=$vars['title']?>" class="form-control pl-2 border-0"/>
        </div>
        <?php if(!empty($vars['errors']) && isset($vars['errors']['title'])):?>
            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['title']?></p>
        <?php endif ?>
    </div>

    <!-- ALT -->
    <div class="form-group col-lg-8 pb-1">
        <label for="alt">Alt</label>
        <div class="border-bottom p-0">
            <input type="text" name="alt" id="alt" value="<?=$vars['alt']?>" class="form-control w-100 pl-2 border-0" placeholder="Photo d'un rameur"/>
        </div>
        <small class="text-secondary">Le <b>alt</b> sert à l'audio-description des images pour les non-voyants.</small>
        <?php if(!empty($vars['errors']) && isset($vars['errors']['alt'])):?>
            <p class="text-danger mb-0 pt-1"><?=$vars['errors']['alt']?></p>
        <?php endif ?>
    </div>
</div>

<!-- ORDRE AFFICHAGE -->
<div class="form-group col-md-4 pb-4 mb-0">
    <label for="position">Afficher la photo en position...</label>
    <div class="col-md-6 border-bottom p-0">
        <select class="custom-select p-2" id="position" name="position">
            <option value="1" <?php if(array_key_exists('id',$_GET) && $vars['position'] == 1):?>selected<?php endif ?>>1</option>
            <option value="2" <?php if(array_key_exists('id',$_GET) && $vars['position'] == 2):?>selected<?php endif ?>>2</option>
            <option value="3" <?php if(array_key_exists('id',$_GET) && $vars['position'] == 3):?>selected<?php endif ?>>3</option>
        </select>
    </div>
    <p class="text-secondary mb-0 mt-2">Tu peux mettre 3 photos au <b>total</b>.</p>
    <?php if($vars['position'] == null):?>
        <small class="text-secondary">Pour info tu as déjà <?=$vars['count']['ban_count']?> photo(s).</small>
    <?php endif ?>
</div>

<!-- BOUTON ENVOYER / MODIFIER ? -->
<div class="form-group col-md-12">
    <button type="submit" class="btn btn-primary mt-3"><?php echo $vars['id'] ? 'MODIFIER' : 'CREER' ?></button>
</div>

</form>
</div>
